Repository dashinja/project2, pull requests merged in 2019-02, with the labels that each got.

#8 Front end
  .DS_Store
  .vscode/tasks.json
  package-lock.json
  package.json
  public/.DS_Store
  public/assets/.DS_Store
  public/assets/css/_animations.scss
  public/assets/css/_variables.scss
  public/assets/css/main.css
  public/assets/css/main.css.map
  public/assets/css/main.scss
  public/assets/css/style.css
  public/assets/images/arrows_rotate.png
  public/assets/images/cityPano.jpg
  public/assets/index.html
  public/index.html
Labels: enhancement

#16 Front end
  .gitignore
  config/config.json
  package-lock.json
  public/assets/css/_variables.scss
  public/assets/css/main.css
  public/assets/css/main.css.map
  public/assets/css/main.scss
  public/index.html
Labels: enhancement

#24 confirm User entry into database based on user login
  .gitignore
  config/DB/schema.sql
  config/DB/schemaTesting.sql
  routes/apiRoutes.js
  routes/userRoutes.js
  views/users.handlebars
Labels: enhancement

#29 make questions/ routes and /profile routes
  routes/apiRoutes.js
Labels: enhancement

#30 Front end
  public/assets/css/main.css
  public/assets/scss/_animations.scss
  public/assets/scss/_mediaQueries.scss
  public/assets/scss/_secondPage.scss
  public/assets/scss/_thirdpage.scss
  public/assets/scss/main.scss
  public/bootstrap.html
  public/bootstrappage3.html
  public/index.html
Labels: enhancement

#32 Updated Routes
  models/user.js
  routes/apiRoutes.js
Labels: enhancement, help wanted

#33 Front end
  package.json
  public/assets/css/main.css
  public/assets/scss/_animations.scss
  public/assets/scss/_thirdpage.scss
  public/assets/scss/main.scss
  public/bootstrap.html
  public/bootstrappage3.html
Labels: enhancement

#34 corrected /api/questions/livingPlaces naming error
  routes/apiRoutes.js
Labels: bug

#42 Api refactoring
  config/passport.js
  config/strategies/google.strategy.js
  config/strategies/local.strategy.js
  models/notes.js
  models/user.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  routes/authRoutes.js
  routes/htmlRoutes.js
  routes/userRoutes.js
  server.js
  views/404.handlebars
  views/error.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/profile.handlebars
  views/questions.handlebars
  views/signIn.handlebars
  views/signUp.handlebars
Labels: enhancement, help wanted

#44 Long build
  config/config.json
  config/passport.js
  config/socket.io.js
  config/strategies/google.strategy.js
  config/strategies/local.strategy.js
  models/chat.js
  models/indexPage.js
  models/indexTestimonial.js
  models/note.js
  models/notes.js
  models/testimonial.js
  models/user.js
  package.json
  public/js/admin.js
  public/js/index.js
  public/js/profile.js
  public/js/questions.js
  routes/adminRoutes.js
  routes/apiRoutes.js
  routes/authRoutes.js
  routes/htmlRoutes.js
  routes/profileRoutes.js
  server.js
  views/admin.handlebars
  views/error.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/profile.handlebars
  views/questions.handlebars
  views/signIn.handlebars
  views/signUp.handlebars
Labels: High Priority Icebox, bug, enhancement, help wanted

#51 Long build
  config/DB/cost-of-living-2016.csv
  config/DB/major-salaries.csv
  config/DB/seedCostOfLiving.js
  config/DB/seedMajorSalaries.js
  config/TD/costTd.csv
  config/TD/costTd.js
  config/TD/majorTd.js
  models/costOfLiving.js
  models/major.js
  models/majorSalaries.js
  package.json
  public/js/Chart.js
  public/js/stats.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  routes/profileRoutes.js
  routes/userRoutes.js
  server.js
  views/profile.handlebars
  views/stats.handlebars
Labels: enhancement

#54 Front end fixes
  views/admin.handlebars
  views/index.handlebars
  views/profile.handlebars
  views/questions.handlebars
  views/stats.handlebars
Labels: enhancement, help wanted

#55 Day of deploy
  views/admin.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/profile.handlebars
  views/stats.handlebars
Labels: enhancement
